## 2D Array Creation

In [1]:
import numpy as np

In [7]:
a=[[1,2,3],[5,6,7],[8,9,10]]

In [11]:
A=np.array(a)
A

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [15]:
#Number of dimension - number of nested lists (a list contain another set of list)
A.ndim

2

In [16]:
#Shape
A.shape

(3, 3)

In [18]:
#Size
A.size #3x3

9

## Indexing and Slicing

In [22]:
#Index A[row][col]/A[row,col]
A[1][1]

6

In [23]:
A[0][2]

3

In [24]:
A[0,2]

3

In [25]:
#Slicing
A[0,0:2]

array([1, 2])

## Basic Operation

In [27]:
#Add
x=np.array([[1,0],[0,1]])
y=np.array([[2,1],[1,2]])

x+y

array([[3, 1],
       [1, 3]])

In [28]:
#Multiple by scalar
2*y

array([[4, 2],
       [2, 4]])

In [29]:
#Product of 2 arrays
x*y

array([[2, 0],
       [0, 2]])

In [34]:
#Matrix multiplication 
# A=2x3 B=3x1 --> 2x1 (col of A must have same number of row in B)
A=np.array([[1,2,3],[4,5,6]]) #2x3
B=np.array([[1,1],[2,2],[3,3]]) #3x2
C=np.dot(A,B) #[[1*1+2*2+3*3, 1*1+2*2+3*3],[4*1+5*2+6*1, 4*1+5*2+6*1]]
C

array([[14, 14],
       [32, 32]])